### ISSUE TITLE
split `cm-matched-string` into two css classes

### ISSUE THREAD

**Issue by chrisgrieser** [nothingislost/obsidian-dynamic-highlights#13]
with the latest update, matches to the current string + matches to the current selection both get `cm-matched-string` class. this makes it impossible to style them separately, even though it would be useful to use more subtle styling for current-string-matches and more emphasized styling for current-selection-matches.

**Comment by nothingislost** [comment]
Added back `cm-matched-word` and `cm-current-word` in 0.1.1

**Comment by chrisgrieser** [comment]
thanks :)
