### ISSUE TITLE
Permanent highlights should ignore YAML + codeblocks

### ISSUE THREAD

**Issue by chrisgrieser** [nothingislost/obsidian-dynamic-highlights#17]
I noticed that the plugin also applies permanent highlights to the yaml header and code blocks, where it leads to tons of highlights that are actually distracting rather than helpful, since words and punctuation have a different meaning there as opposed to "normal" markdown text, resulting in mostly unwanted highlights.

I'd simply suggest to have the plugin's permanent highlights ignore yaml and code blocks. Either permanently, or with a toggle (which should probably be on by default).

**Comment by nothingislost** [comment]
Implemented in 0.1.3

**Comment by chrisgrieser** [comment]
🥳

**Comment by Cammagno** [comment]
I support the request to add a toggle to re-enable it in code :)
