### ISSUE TITLE
[BUG]: `Esc` key does not work in the Settings tab

### ISSUE THREAD

**Issue by chrisgrieser** [nothingislost/obsidian-dynamic-highlights#30]
When I am in the Dynamic Highlights Settings Tab, I cannot close the window anymore by pressing `Esc`.

(+ Rip me since my theme removes the close buttons 😆 )

```
macOS 12.0.1
Obsidian 0.13.19
```

**Comment by nothingislost** [comment]
Addressed in v0.2.2
