### ISSUE TITLE
Performance observation

### ISSUE THREAD

**Issue by lishid** [nothingislost/obsidian-dynamic-highlights#36]
Reported by @kometenstaub

There might be a performance issue where this line is repeatedly setting up a requestAnimationFrame and consuming CPU when nothing is happening:
https://github.com/Simonwep/pickr/blob/411cb1d214f961e0238ad72fecf6abf3e99113ca/src/js/pickr.js#L147

Seems to come from a dependency and we traced the issue to this plugin. Not sure if there are any specific repro steps but it doesn't always happen.

**Comment by lishid** [comment]
Update: Seems to be related to https://github.com/valentine195/obsidian-settings-search which sets up each setting's tab in the background to index the search.

**Comment by nothingislost** [comment]
So who's issue are we considering this? :)

**Comment by lishid** [comment]
I'd pin it on the picker because it's written poorly.

In the case where it's never put into DOM, it would infinite loop requestAnimationFrame which is a really poor way of detecting when an element is inserted into the DOM.

Given that you're including the library in this plugin (and I'm also seeing it in Highlightr) I think it's best if you either patch it up here, submit a patch upstream, or use a different library, unless you have a better suggestion?

**Comment by nothingislost** [comment]
I chose Pickr because Style Settings is using it. That's probably the most popular plugin using it currently. 

I haven't really looked at the internals of Pickr but I'll take a look at that requestAnimationFrame behavior and see if it makes sense to patch it or move to a different library.

**Comment by lishid** [comment]
Ok fair enough. Maybe we should also tag @mgmeyers and @chetachiezikeuzor for a collaboration.

**Comment by nothingislost** [comment]
Looks like Pickr is no longer maintained so patching it is less of an option unless we fork it which I'm not super interested in doing. I did a quick look and https://github.com/mdbassit/Coloris seems interesting. I did a quick search and there's no reference to `requestAnimationFrame` in their codebase at least ;) I'll try it out and follow up with some porting instructions if it works out.

**Comment by mgmeyers** [comment]
Blerg. I recently saw that pickr is no longer being maintained and wanted to swap it out for something else. This just gives me another reason!

**Comment by mgmeyers** [comment]
@nothingislost Let me know how Coloris works out for you. Cecilia May recommended iro.js as another option: https://github.com/mgmeyers/obsidian-style-settings/issues/50

**Comment by ebullient** [comment]
As an _interesting offshoot_ ... @lishid, it would be nice if we could have a color picker as one of the controls provided by obsidian. You need a picker, too, for graph node colors. I would *LOVE* to just have one that handles cut/paste and alphas and things such that I don't have to care. ;) Then snippetor and style settings and dynamic highlights and admonitions and (however many more plugins use colors that I haven't thought of) can all have a consistent experience.

**Comment by nothingislost** [comment]
Pickr fork: https://github.com/nothingislost/pickr/tree/a17739f7aa1871b44da778cbb79ae76dae77d839

Settings Search patch: https://github.com/valentine195/obsidian-settings-search/pull/7
Dynamic Highlights patch: https://github.com/nothingislost/obsidian-dynamic-highlights/commit/b7248e17f04f0ce5666bbbd4fcc43d45dbdfac64
Style Settings patch: https://github.com/mgmeyers/obsidian-style-settings/pull/60
