### ISSUE TITLE
Bug：Conflict with obsidian-advanced-slides

### ISSUE THREAD

**Issue by tyf2018** [nothingislost/obsidian-dynamic-highlights#43]
Your plugin is very useful, but I'm afraid I have another compatibility issue to report.

This plugin will conflict with obsidian-advanced-slides, which will cause obsidian-advanced-slides preview results to not display any content. After closing Dynamic Highlights, it returns to normal.

obsidian-advanced-slides address: https://github.com/MSzturc/obsidian-advanced-slides

Best regards.

**Comment by nothingislost** [comment]
Are you using Dynamic Highlights v0.2.5? If so, I'll need more detailed reproduction steps/screenshots as I can not seem to replicate this issue.

**Comment by tyf2018** [comment]
> Are you using Dynamic Highlights v0.2.5? If so, I'll need more detailed reproduction steps/screenshots as I can not seem to replicate this issue.

Update to version 0.25 and the problem is solved. Thanks!

However, the update of version 0.25 does not seem to be pushed in obsidian's third-party plug-in market, and it needs to be updated manually.

**Comment by nothingislost** [comment]
Oops, thanks for the heads up on the plugin version. That's been fixed.
