### ISSUE TITLE
Documentation: Can we get an example of CSS in the UI ?

### ISSUE THREAD

**Issue by brimwats** [nothingislost/obsidian-dynamic-highlights#62]
Hi! Thanks for your work on this. I'm trying to figure out how to add custom CSS. I see your json examples but that hasn't helped me set CSS in the settings. I've tried just 'strong' 'text-decoration: line-through;' 'background: black' and variations but none seem to work. Just an example wold help me identify what CSS goes in there (like.. do I add root:? I don't think so—do I add the cssclass?).

Thanks!

**Comment by nothingislost** [comment]
Write styles in the CSS editor just like you would if you were writing a css snippet. You still need to call out the class names you want to style and such.

```css
.inline-property-name {
color: var(--text-faint);
font-size: 0.8em;
}
```

**Comment by brimwats** [comment]
thanks a ton—that clears it up!
