### ISSUE TITLE
Bug: Failed to load plugin obsidian-dynamic-highlights in new version of Obsidian

### ISSUE THREAD

**Issue by hustrjh** [nothingislost/obsidian-dynamic-highlights#65]
## Bug
I just updated Obsidian from v0.14.15 to v0.15.6. Then some plugins including `dynamic-highlights` can't work normally.
## Picture
![image](https://user-images.githubusercontent.com/69783980/178883324-0306be96-5e49-4250-80cd-2158f3f76e9e.png)

**Comment by hustrjh** [comment]
Actually the version of the plugin I tested was **`v0.2.5`**. After I updated the plugin to **`v0.3.1`**, it can work normally. Maybe @nothingislost need to release the official edition instead of pre-release version. Thank you anyway!

**Comment by nothingislost** [comment]
0.3.1 is what's available in the official community plugins store

**Comment by hustrjh** [comment]
OK. Thanks！
