### ISSUE TITLE
Come up with a new plugin name

### ISSUE THREAD

**Issue by nothingislost** [nothingislost/obsidian-dynamic-highlights#7]
Highlight Current Word no longer describes the plugin. What should it be called now? 

- Contextual Highlights?
- Selection Highlighter?

Open to suggestions.

**Comment by chrisgrieser** [comment]
in case you implement something like #8, "Semantic Highlights" would come to mind? 🤔 

However, I like "Contextual Highlight" best, tbh.

**Comment by nothingislost** [comment]
I'm down to
1. Smart Highlights
2. Contextual Highlights
3. Dynamic Highlights

leaning towards Dynamic Highlights at this point

**Comment by chrisgrieser** [comment]
I think 2. + 3. both are fine
