### ISSUE TITLE
FR: Permanent Highlight of certain words?

### ISSUE THREAD

**Issue by chrisgrieser** [nothingislost/obsidian-dynamic-highlights#8]
I was playing around with the data attribute and realized this should rather be a plugin feature to be more flexible.

So the idea is to stray a bit away form the "word where the cursor is" idea but instead *permanently* highlighting certain words. One use case could be to automatically apply strikethroughs to filler words. Another one I can think of is to highlight conjunctions ("and", "or", "but", etc.), which would help with recognizing sentence structures at glance. (In most languages, sentences are longer than in English.)

both features would be great features for writers to have. They would stray away from the original idea of this plugin a bit, but nevertheless probably be based on a very similar code base, so it would probably make sense to add this feature to this plugin?

**Comment by nothingislost** [comment]
Aren't we treading into the territory of SkepticMystic's NLP plugin? Can it not do this?

**Comment by chrisgrieser** [comment]
hmmm, you are right. that feature could work in both plugins, I guess. Well, your plugin, your decision 🙂

**Comment by nothingislost** [comment]
I'll leave the fancy language analysis to SkepticMystic but persistent highlighting based on static, user defined, strings I think is reasonable

**Comment by claremacrae** [comment]
> I'll leave the fancy language analysis to SkepticMystic but persistent highlighting based on static, user defined, strings I think is reasonable

I'm currently looking to highlight card-board plugin-related strings, for example:

```
@due(2022-01-03)
@completed(2021-12-26T13:10:46)
```

Even just having the `@due` and `@completed` would be really useful - but lovelier still would be for regular expressions to be supported, and to be able to chose the highlighting colour for each pattern.

**Comment by nothingislost** [comment]
@claremacrae @chrisgrieser would you like to provide input on how these static string will be marked in the dom?

I have regex highlighting working but I'm trying to decide what the UX will be and how to mark the matches.

Would it be sufficient to have a plugin settings section that does something along the lines of:

<button>Add new static highlighter<button>
class name: ______________
regex string: ______________

with the ability to add an arbitrary number of highlighters? the DOM would then apply the specified class name to any string that matched the regex string.

Let me know if you have other thoughts.

**Comment by claremacrae** [comment]
@nothingislost Thank you for doing this, and thank you for asking!

I was thinking of something like:

search term: ----------  [x] regular expression
colour: ffaabb [color picker button]

So:

1. the term to search for
    * with a checkbox option to make it a regex - so no need to escape complex characters if it's a consistent string
2. the colour to use to highlight it
    * with a colour-picker to chose it

How were you thinking the class in the DOM would be used? Would users be needing to provide and enable their own CSS snippets, or would your plugin be doing that?

**Comment by chrisgrieser** [comment]
Pretty much what Clare said. For some use cases, you would want to have the same highlight, for others you word want to have different highlights. 

Also maybe a toggle to switch between emphasizing by highlight or by text color? 🤔 

And add a cssclass per query, for users who want to make their own style via css

**Comment by nothingislost** [comment]
Thanks for the input! I assume you also want a data attribute containing the matched string value?

**Comment by chrisgrieser** [comment]
Hmm, I am wondering what the use case for that would be? If I want different styling, I'd be able to split it up into multiple queries, wouldn't I?

Well, I can't think of a reason, but it probably also wouldn't hurt in case someone else comes up with a reason and it's no effort for you to implement? 🤔

**Comment by claremacrae** [comment]
> Thanks for the input! I assume you also want a data attribute containing the matched string value?

I don't think it matters, but I don't understand the question!

**Comment by nothingislost** [comment]
The first draft of this has been delivered in 0.1.0. Expect breaking changes. Check out the readme for more details.

**Comment by chrisgrieser** [comment]
I tried it out and it works great for me. For the wider audience, however, I'd suggest making some simplifications though:
- the purpose of assigning a css class is unclear (and for 99% of users who are not going to use custom css snippets, it's also irrelevant). Maybe just call it "name" with a brief info that this will be the css class?
- it's unclear that the selected color are background colors (also, an option for text color/underlines etc. would be useful for users not adept in CSS)
- rather than "query", I'd write "term" in the input placeholder. Maybe switch to "expression" when regex is enabled?
- it's not clear from the UI that you can drag-an-drop to re-arrange order
- especially for more complex regexes, being able to edit a query would be useful.

**Comment by nothingislost** [comment]
Thanks for the feedback. Much of this has been incorporated into v0.1.2

**Comment by claremacrae** [comment]
Sorry I haven't had a chance to test this yet, but I really appreciate the work, and the feedback given - thank you!

**Comment by nothingislost** [comment]
I'm going to close this one out. If you all think of anything else, please raise it as a new issue.

**Comment by claremacrae** [comment]
Wow, this is absolutely amazing in Edit modes - thank you!

Is there anything I can do to make it work in Reading mode? Does it need to be a feature of the Theme I'm using?

**Comment by chrisgrieser** [comment]
@claremacrae see #26
